config/routes.rb
Campbeat::Application.routes.draw do
  devise_for :users, :path_names => { 
    :sign_in => 'login', 
    :sign_out => 'logout' 
  }
  
  devise_scope :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  resources :campers
  
  resources :camps do
    match 'register' => "registrations#show", :via => :get
    match 'create_registration' => "registrations#create", :via => :post
    
    scope :module => "camp" do
      resources :campers do
        scope :module => "campers" do
          resources :sessions
        end
      end

      resources :contacts
      resources :sessions
      resources :programs
      resources :parents
    end
  end

  match '/:controller(/:action(/:id))'
  
  root :to => "pages#index"
end

app/models/camp.rb
class Camp < ActiveRecord::Base

  # Mass Assignment Whitelist
  # =========================
  attr_accessible :address_attributes, :email_address, :name , :uri

  # Associations
  # ============
  has_many :contacts, :as => :contactable
  has_many :programs
  has_many :sessions
  
  has_and_belongs_to_many :campers
  has_and_belongs_to_many :users

  has_one :address, :as => :addressable, :dependent => :destroy
  accepts_nested_attributes_for :address, :allow_destroy => true
  
  # Validations
  # ===========
  validates :email_address, :email => true, :allow_nil => true
  validates :name, :presence => true 
  validates :uri, :presence => true, :uniqueness => true
  #validates :address, :associated => true
  
  # Public Methods
  # ==============

  # overriding this method makes sure that rails uses the URI attribute of a 
  # camp instead of its id when creating url paths.
  #
  def to_param
    uri
  end
end

app/controllers/camp/campers/sessions_controller.rb
class Camp::Campers::SessionsController < AuthorizedController
  skip_load_and_authorize_resource
  before_filter :get_camp
  authorize_resource :camp
  before_filter :get_camper
  authorize_resource :camper
  before_filter :get_session, :only => [:show, :update, :destroy]
  authorize_resource :session 
  
  
  # == GET /camps/{camp_uri}/campers/{camper_id}/sessions/{session_id}
  # 
  # Returns a list of all the campers attending the camp referenced by {camp_uri}
  #
  # === Response Codes:
  #
  # * 200 OK
  # * 401 Unauthorized
  # * 404 Not Found
  #
  # === Supported Content Types: *TODO*
  #
  # * XML
  # * JSON
  #
  # === Example XML Response:
  #
  #    <camper>
  #        <camper-uri>https://www.vertizu.com/campers/fhs48htos4h</camper-uri>
  #        <session-uri>https://www.vertizu.com/sessons/djw39rh48</session-uri>
  #        <program-uri>https://www.vertizu.com/programs/fj4ih48w</program-ur>
  #        <cabin-uri>https://www.vertizu.com/cabins/ajf8fus</cabin-uri>
  #        <schedule-uri>https://www.vertizu.com/campers/fhs48htos4h/sessions/djw39rh48/schedule</schedule-uri>
  #    </camper>
  #
  def show
    ca = CamperAttendance.where("camper_id = ? AND session_id = ?", @camper.id, @session.id).limit(1)[0]
    @program = ca.program
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml #show.xml.builder
      format.json { render :template => "camp/campers/sessions/show.json" }
    end
  end

  # == PUT /camps/{camp_uri}/campers/{camper_id}/sessions/{session_id}
  #
  # Update the program that the camper is attending.
  #
  # === Response Codes:
  #
  # * 202 Accepted
  # * 400 Bad Request
  # * 401 Unauthorized
  # * 404 Not Found
  #
  # === Supported Content Types: *TODO*
  #
  # * XML
  # * JSON
  #
  # === Parameters:
  #
  # *Required*: *TODO* 
  # * <tt>program-id {String}</tt> - The id of the program the camper will attend
  # * <tt>cabin-id {String}</tt> - The id of the cabin the camper will stay in
  #
  # === Example XML Response:
  #
  #    <camper>
  #        <program-uri>https://www.vertizu.com/programs/fj4ih48w</program-ur>
  #        <cabin-uri>https://www.vertizu.com/cabins/ajf8fus</cabin-uri>
  #    </camper>
  #
  def update
    if params[:program_id].nil? or !@camp.programs.exists?(params[:program_id])
      respond_to do |format|
        format.html { render :action => "edit", :status => :bad_request }
        format.xml  { render :xml => @session.errors, :status => :bad_request }
      end
    else
      program = @camp.programs.find(params[:program_id])
      if program.is_valid_age(@camper.age)
        ca = CamperAttendance.where("camper_id = ? AND session_id = ?", @camper.id, @session.id).limit(1)[0]

        program_pop = ProgramPopulation.where("program_id = ? AND session_id = ?", ca.program_id, @session.id).limit(1)[0]
        program_pop.decrement!(:current_population)
      
        ca.program_id = params[:program_id]
        program_pop = ProgramPopulation.where("program_id = ? AND session_id = ?", params[:program_id], @session.id).limit(1)[0]
        
        if program_pop
          program_pop.increment!(:current_population)
          isSuccess = ca.save!

          if isSuccess
            respond_to do |format|
              format.html { render :text => "you have updated the registered camper", :status => :accepted }
              format.xml  { head :accepted }
            end
          else
            respond_to do |format|
                format.html { render :action => "edit", :status => :internal_server_error }
                format.xml {render :xml => @session, :status => :internal_server_error, :location => @camper}
            end
          end
        else
          respond_to do |format|
              format.html { render :action => "edit", :status => :bad_request }
              format.xml {render :xml => @camper, :status => :bad_request, :location => @session}
          end
        end
      else
        respond_to do |format|
            format.html { render :action => "edit", :status => :bad_request }
            format.xml {render :xml => @camper, :status => :bad_request, :location => @session}
        end
      end
    end
  end

  # == DELETE /camps/{camp_id}/contacts/{id}
  #
  # Remove the camper from attending a given session
  #
  # === Response Codes: *TODO*
  #
  # * 202 Accepted
  # * 400 Bad Request
  # * 401 Unauthorized
  #
  def destroy
    ca = CamperAttendance.where("camper_id = ? AND session_id = ?", @camper.id, @session.id).limit(1)[0]
    
    program_pop = ProgramPopulation.where("program_id = ? AND session_id = ?", ca.program_id, @session.id).limit(1)[0]
    program_pop.decrement!(:current_population)
    
    ca.destroy
    
    if ca.destroyed?
      respond_to do |format|
        format.html { render :text => "you have updated the registered camper", :status => :accepted }
        format.xml  { head :accepted }
      end
    end
  end
  
  private
    def get_camp
      @camp = Camp.find_by_uri(params[:camp_id])
      if !@camp
        #call parent 404 method because no record was found
        #ActiveRecord::RecordNotFound is not being called
        self.render_404
      end
    end
    
    def get_camper
      @camper = @camp.campers.find(params[:camper_id])
      if !@camper
        #call parent 404 method because no record was found
        #ActiveRecord::RecordNotFound is not being called
        self.render_404
      end
    end
    
    def get_session
      @session = @camper.sessions.find(params[:id])
      if !@session
        #call parent 404 method because no record was found
        #ActiveRecord::RecordNotFound is not being called
        self.render_404
      end
    end
end

app/controllers/camp/campers_controller.rb
class Camp::CampersController < AuthorizedController
  skip_load_and_authorize_resource
  before_filter :get_camp
  before_filter :get_campers, :only => [:index]
  before_filter :get_camper, :only => [:show, :edit, :update, :destroy]
  authorize_resource :camp
  load_and_authorize_resource :camper, :through => :camp
  
  # == GET /camps/{camp_uri}/campers
  #
  # *TODO*: manage content-type of response by monitoring Accept header of the request
  # 
  # Returns a list of all the campers attending the camp referenced by {camp_uri}
  #
  # === Response Codes: *TODO*
  #
  # * 200 OK
  # * 400 Bad Request
  # * 401 Unauthorized
  # * 404 Not Found
  #
  # === Supported Content Types: *TODO*
  #
  # * XML
  # * JSON
  #
  # === Parameters:
  #
  # *Optional*:
  # * <tt>name {String}</tt> - The name of a camper
  # * <tt>min_age {Integer}</tt> - Returns all campers that are greater than or equal to the given age
  # * <tt>max_age {Integer}</tt> - Returns all campers that are less than or equal to the given age
  # * <tt>grade {Integer}</tt> - Returns all campers that are in the given school grade
  # * <tt>gender {Char}</tt> - Returns all campers that are of the given gender. Can be M or F.
  # * <tt>cabin {String}</tt> - *TODO* Returns all campers that are in the given cabin.
  # * <tt>program_id {String}</tt> - Using a program id, Returns a list of all campers attending the given program
  # * <tt>program_name {String}</tt> - Using a program's name, Returns a list of all campers attending the given program
  # * <tt>session_id {String}</tt> - Using a session id, Returns a list of all campers attending the given session
  #
  # === Example XML Response:
  #    <campers>
  #      <camper>
  #        <id>fw484w4wh</id> 
  #        <first-name>Nathan</first-name>
  #        <middle-name>L</middle-name>
  #        <last-name>Gersbach</last-name>
  #        <suffix>Jr.</suffix>
  #        <age>12</age>
  #        <birthday>06-27-1999</birthday>
  #        <grade>6</grade>
  #        <gender>M</gender>
  #        <guardians>
  #            <guardian>https://vertizu.com/parents/fn48tfhsu<guardian>
  #            <guardian>https://vertizu.com/parents/fn48tfhsu<guardian>
  #        </guardians>
  #        <address>
  #            <street>501 Dehart St</street>
  #            <town>Blacksburg</town>
  #            <state>VA</state>
  #            <zip-code>24060</zip-code> 
  #            <country>USA</country>
  #       </address>
  #       <sessions>
  #            <session-id>f48wfh8</session-id> 
  #       </sessions>
  #      </camper>
  #    <campers>
  #
  def index
    query = ''
    append_to_query(query, 'grade = :grade') if params[:grade]
    append_to_query(query, 'gender = :gender') if ['M', 'F', 'm', 'f'].include?(params[:gender])

    if (query.length > 0)
      @campers = @camp.campers.where(query, params)
    else
      @campers = @camp.campers
    end

    # '<=' because we are comparing by years, so min age will determine the max year in which a person is born
    # vice versa for max_age
    @campers = @campers.where( "birthday <= ?", Time.utc(Time.now.year - params[:min_age].to_i) ) if params[:min_age]
    @campers = @campers.where( "birthday >= ?", Time.utc(Time.now.year - params[:max_age].to_i) ) if params[:max_age]
    
    @campers = @campers.joins(:programs).where('programs.id = ?', params[:program_id]) if params[:program_id]
    @campers = @campers.joins(:programs).where('programs.name = ?', params[:program_name]) if params[:program_name]
    @campers = @campers.joins(:sessions).where('sessions.id = ?', params[:session_id]) if params[:session_id]
      
    if @campers
      respond_to do |format|
        format.html # index.html.erb
        format.xml
        format.json{ render :template => "camp/campers/index", :formats => [:json] }
      end
    else
      respond_to do |format|
        format.html { render :action => "index", :status => :bad_request }
        format.xml  { render :xml => @campers.errors, :status => :bad_request }
      end
    end
  end

  # == POST /camps/{camp_uri}/campers
  #
  # Register a camper with the camp.
  #
  # === Response Codes: *TODO*
  #
  # * 201 Created
  # * 400 Bad Request
  # * 401 Unauthorized
  # * 404 Not Found
  #
  # === Supported Content Types: *TODO*
  #
  # * XML
  # * JSON
  #
  # === Parameters:
  #
  # *Required*: *TODO* 
  # * <tt>program-id {String}</tt> - The id of the program the camper will attend
  # * <tt>session-id {String}</tt> - The id of the session the programmer will attend
  #
  # === Example XML Response:
  #
  #    <camper>
  #        <id>fw484w4wh</id>
  #        <programs> 
  #            <program>
  #                <program_id>dn3iwrh8</program_id>
  #                <session_id>f48wfh8</session_id> 
  #            </program>
  #        <programs>
  #    </camper>
  #
  def create
    if @camp.campers.exists?(params[:camper_id])
      error(409, 409, "The camper is already registered with the camp")
    else
      @camper = Camper.find(params[:camper_id])

      if params[:programs].nil?
        respond_to do |format|
          format.html { render :action => "new", :status => :bad_request }
          format.xml  { render :xml => @camper.errors, :status => :bad_request }
        end
      else
        resultHash = register_camper_with_program(params[:programs])
        
        unless resultHash[:success].empty?
           @camp.campers << @camper

            respond_to do |format|
                format.html { render :text => "camper registered!", :status => :created }
                format.xml {render :status => :created, :location => @camper}
            end
        else 
          respond_to do |format|
              format.html { render :action => "new", :status => :bad_request }
              format.xml {render :status => :bad_request, :location => @camper}
          end
        end
      end
    end
  end

  # == GET /camps/{camp_uri}/campers/{camper_id}
  #
  # *TODO*: manage content-type of response by monitoring Accept header of the request
  # 
  # Returns a list of all the campers attending the camp referenced by {camp_uri}
  #
  # === Response Codes: *TODO*
  #
  # * 200 OK
  # * 401 Unauthorized
  # * 404 Not Found
  #
  # === Supported Content Types: *TODO*
  #
  # * XML
  # * JSON
  #
  # === Example XML Response:
  #
  #      <camper>
  #        <id>fw484w4wh</id> 
  #        <first-name>Nathan</first-name>
  #        <middle-name>L</middle-name>
  #        <last-name>Gersbach</last-name>
  #        <suffix>Jr.</suffix>
  #        <age>12</age>
  #        <birthday>06-27-1999</birthday>
  #        <grade>6</grade>
  #        <gender>M</gender>
  #        <parents>
  #            <parent-uri>https://vertizu.com/parents/fn48tfhsu<parent-uri>
  #            <parent-uri>https://vertizu.com/parents/fn48tfhsu<parent-uri>
  #        </parents>
  #        <emergency-contacts>
  #            <parent-uri>https://vertizu.com/parents/fn48tfhsu<parent-uri>
  #            <parent-uri>https://vertizu.com/parents/fn48tfhsu<parent-uri>
  #        </emergency-contacts>
  #        <address>
  #            <street>501 Dehart St</street>
  #            <town>Blacksburg</town>
  #            <state>VA</state>
  #            <zip-code>24060</zip-code> 
  #            <country>USA</country>
  #       </address>
  #       <sessions>
  #            <session-id>f48wfh8</session-id> 
  #       </sessions>
  #      </camper>
  #
  def show
    if !@camper
      #call parent 404 method because no record was found
      #ActiveRecord::RecordNotFound is not being called
      self.render_404 
    else
      
      @sessions = @camper.sessions.where('camp_id = ?', @camp.id)
      
      respond_to do |format|
        format.html # show.html.erb
        format.xml  # show.xml.builder
        format.json{ render :template => "camp/campers/show", :formats => [:json], :handlers => :erb }
      end
    end
  end

  # == PUT /camps/{camp_uri}/campers
  #
  # Update the sessions and programs that the camper is attending.
  # A request to this service will add programs and sessions
  # the user is attending.
  #
  # === Response Codes: *TODO*
  #
  # * 202 Accepted
  # * 400 Bad Request
  # * 401 Unauthorized
  #
  # === Supported Content Types: *TODO*
  #
  # * XML
  # * JSON
  #
  # === Parameters:
  #
  # *Required*: *TODO* 
  # * <tt>program-id {String}</tt> - The id of the program the camper will attend
  # * <tt>session-id {String}</tt> - The id of the session the programmer will attend
  #
  # === Example XML Response:
  #
  #    <camper>
  #        <id>fw484w4wh</id>
  #        <programs> 
  #            <program>
  #                <program-id>dn3iwrh8</program-id>
  #                <session-id>f48wfh8</session-id> 
  #            </program>
  #        <programs>
  #    </camper>
  #
  def update
    if params[:programs].nil?
      respond_to do |format|
        format.html { render :action => "edit", :status => :bad_request }
        format.xml  { render :xml => @camper.errors, :status => :bad_request }
      end
    else
      resultHash = register_camper_with_program(params[:programs])

      unless resultHash[:success].empty?
          respond_to do |format|
            format.html { render :text => "you have updated the registered camper", :status => :accepted }
            format.xml  { head :accepted }
          end
      else 
        respond_to do |format|
            format.html { render :action => "edit", :status => :bad_request }
            format.xml {render :xml => @camper, :status => :bad_request, :location => @camper}
        end
      end
    end
  end

  def edit
    if not (@camper.nil?)
      respond_to do |format|
        format.html  { render :template => 'camp/campers/edit'}
      end
    end
  end
  
  private
    def get_camp
      @camp = Camp.find_by_uri(params[:camp_id])
      if !@camp
        #call parent 404 method because no record was found
        #ActiveRecord::RecordNotFound is not being called

app/helpers/camp/campers/sessions_helper.rb
module Camp::Campers::SessionsHelper
end

app/helpers/camp/campers_helper.rb
module Camp::CampersHelper
end

app/helpers/camps_helper.rb
module CampsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/camp/programs/edit.html.erb
<h1>Editing program</h1>

<%= form_for [@camp, @program] do |f| %>
  
  <% @program.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :min_age %><br />
    <%= f.text_field :min_age %>
  </p>
  <p>
    <%= f.label :max_age %><br />
    <%= f.text_field :max_age %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', camp_program_path(@camp,@program) %> |
<%= link_to 'Back', camp_programs_path %>

app/views/camp/programs/index.html.erb
<h1>Listing programs</h1>

<table>
  <tr>
    <th>Camp</th>
    <th>Name</th>
    <th>Description</th>
    <th>Min age</th>
    <th>Max age</th>
    <th>Cost</th>
	<th>Session Id</th>
	<th>Current Pop.</th>
	<th>Max Pop.</th>
  </tr>

<%= @camp.programs.each do |program| %>
  <tr>
    <td><%=h program.camp %></td>
    <td><%=h program.name %></td>
    <td><%=h program.description %></td>
    <td><%=h program.min_age %></td>
    <td><%=h program.max_age %></td>
    <td><%=h program.price %></td>

	<%= program.program_populations.each do |programPop| %>
		<td><%=h programPop.session_id %></td>
		<td><%=h programPop.current_population %></td>
		<td><%=h programPop.max_population %></td>
	<% end %>
	
    <td><%= link_to 'Show', camp_program_path(@camp, program) %></td>
    <td><%= link_to 'Edit', edit_camp_program_path(@camp, program) %></td>
    <td><%= link_to 'Destroy',[@camp,program], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New program', new_camp_program_path %>

app/views/camp/programs/index.json.erb
[
<% @programs.each_with_index do |program, index| %>
	{
		id: <%= program.id %>,
		camp_uri: "<%= program.camp.uri %>",
		name: "<%= program.name %>",
		description: "<%= program.description %>",
		min_age: <%= program.min_age %>,
		max_age: <%= program.max_age %>,
		price: <%= program.price %>,
		sessions: [
		<% program.program_populations.each_with_index do |pop, index| %>
			{
				session_id: <%= pop.session.id %>,
				current_population: <%= pop.current_population %>,
				max_population: <%= pop.max_population %>
			<% if index == program.program_populations.length-1 then %>
			}
	 		<% else %>
			},
			<% end %>
		<% end %>
		]
	<% if index == @programs.length-1 then %>
	}
	<% else %>
	},
	<% end %>
<% end %>
]

app/views/camp/programs/new.html.erb
<h1>New program</h1>

<%= form_for [@camp, @program] do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :min_age %><br />
    <%= f.text_field :min_age %>
  </p>
  <p>
    <%= f.label :max_age %><br />
    <%= f.text_field :max_age %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
	
  	<%= f.fields_for :program_populations  do |p| %>
		<p>
		  <%= p.label :session_id %><br />
		  <%= p.text_field :session_id %>
		</p>
		<p>
	      <%= p.label :current_population %><br />
		  <%= p.text_field :current_population %>
		</p>
		<p>
	      <%= p.label :max_population %><br />
		  <%= p.text_field :max_population %>
		</p>
	<% end %>

  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', camp_programs_path %>

app/views/camp/programs/show.html.erb
<p>
  <b>Camp:</b>
  <%=h @program.camp %>
</p>

<p>
  <b>Name:</b>
  <%=h @program.name %>
</p>

<p>
  <b>Description:</b>
  <%=h @program.description %>
</p>

<p>
  <b>Min age:</b>
  <%=h @program.min_age %>
</p>

<p>
  <b>Max age:</b>
  <%=h @program.max_age %>
</p>

<p>
  <b>Cost:</b>
  <%=h @program.price %>
</p>


<%= link_to 'Edit', edit_camp_program_path(@camp, @program) %> |
<%= link_to 'Back', camp_programs_path %>

app/views/camp/programs/show.json.erb
{
	id: <%= @program.id %>,
	camp_uri: "<%= @program.camp.uri %>",
	name: "<%= @program.name %>",
	description: "<%= @program.description %>",
	min_age: <%= @program.min_age %>,
	max_age: <%= @program.max_age %>,
	price: <%= @program.price %>,
	sessions: [
	<% @program.program_populations.each_with_index do |pop, index| %>
		{
			session_id: <%= pop.session.id %>,
			current_population: <%= pop.current_population %>,
			max_population: <%= pop.max_population %>
		<% if index == @program.program_populations.length-1 then %>
		}
 		<% else %>
		},
		<% end %>
	<% end %>
	]
}