config/routes.rb
Campbeat::Application.routes.draw do
  devise_for :users, :path_names => { 
    :sign_in => 'login', 
    :sign_out => 'logout' 
  }
  
  devise_scope :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  resources :campers
  
  resources :camps do
    match 'register' => "registrations#show", :via => :get
    match 'create_registration' => "registrations#create", :via => :post
    
    scope :module => "camp" do
      resources :campers do
        scope :module => "campers" do
          resources :sessions
        end
      end

      resources :contacts
      resources :sessions
      resources :programs
      resources :parents
    end
  end

  match '/:controller(/:action(/:id))'
  
  root :to => "pages#index"
end

app/models/camper.rb
class Camper < ActiveRecord::Base

  # Mass Assignment Whitelist
  # =========================
  attr_accessible :first_name, :middle_name, :last_name, :suffix, :gender, 
                  :birthday, :grade, :address_attributes

  # Associations
  # ============
  belongs_to :user
  
  has_one :address, :as => :addressable

  has_many :camper_attendances
  has_many :guardians, :as => :contactable, :class_name => "Contact"  
  has_many :programs, :through => :camper_attendances
  has_many :sessions, :through => :camper_attendances
  
  has_and_belongs_to_many :camps

  accepts_nested_attributes_for :address, :allow_destroy => true
  accepts_nested_attributes_for :guardians, :allow_destroy => true

  # Validations
  # ===========  
  validates :first_name, :presence => true 
  validates :last_name, :presence => true 
  validates :birthday, :presence => true, :timeliness => {:type => :date} 
  validates :gender, :presence => true, :length => { :maximum => 1 }
  validates_inclusion_of :gender, :in => %w(M F m f) 
  
  # Public Methods
  # ==============

  # Get the age of the camper. This method accounts for leap years.
  #
  def age
    now = Time.now.utc.to_date
    now.year - self.birthday.year - ((now.month > self.birthday.month || (now.month == self.birthday.month && now.day >= self.birthday.day)) ? 0 : 1)
  end

end

app/controllers/camp/campers/sessions_controller.rb
class Camp::Campers::SessionsController < AuthorizedController
  skip_load_and_authorize_resource
  before_filter :get_camp
  authorize_resource :camp
  before_filter :get_camper
  authorize_resource :camper
  before_filter :get_session, :only => [:show, :update, :destroy]
  authorize_resource :session 
  
  
  # == GET /camps/{camp_uri}/campers/{camper_id}/sessions/{session_id}
  # 
  # Returns a list of all the campers attending the camp referenced by {camp_uri}
  #
  # === Response Codes:
  #
  # * 200 OK
  # * 401 Unauthorized
  # * 404 Not Found
  #
  # === Supported Content Types: *TODO*
  #
  # * XML
  # * JSON
  #
  # === Example XML Response:
  #
  #    <camper>
  #        <camper-uri>https://www.vertizu.com/campers/fhs48htos4h</camper-uri>
  #        <session-uri>https://www.vertizu.com/sessons/djw39rh48</session-uri>
  #        <program-uri>https://www.vertizu.com/programs/fj4ih48w</program-ur>
  #        <cabin-uri>https://www.vertizu.com/cabins/ajf8fus</cabin-uri>
  #        <schedule-uri>https://www.vertizu.com/campers/fhs48htos4h/sessions/djw39rh48/schedule</schedule-uri>
  #    </camper>
  #
  def show
    ca = CamperAttendance.where("camper_id = ? AND session_id = ?", @camper.id, @session.id).limit(1)[0]
    @program = ca.program
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml #show.xml.builder
      format.json { render :template => "camp/campers/sessions/show.json" }
    end
  end

  # == PUT /camps/{camp_uri}/campers/{camper_id}/sessions/{session_id}
  #
  # Update the program that the camper is attending.
  #
  # === Response Codes:
  #
  # * 202 Accepted
  # * 400 Bad Request
  # * 401 Unauthorized
  # * 404 Not Found
  #
  # === Supported Content Types: *TODO*
  #
  # * XML
  # * JSON
  #
  # === Parameters:
  #
  # *Required*: *TODO* 
  # * <tt>program-id {String}</tt> - The id of the program the camper will attend
  # * <tt>cabin-id {String}</tt> - The id of the cabin the camper will stay in
  #
  # === Example XML Response:
  #
  #    <camper>
  #        <program-uri>https://www.vertizu.com/programs/fj4ih48w</program-ur>
  #        <cabin-uri>https://www.vertizu.com/cabins/ajf8fus</cabin-uri>
  #    </camper>
  #
  def update
    if params[:program_id].nil? or !@camp.programs.exists?(params[:program_id])
      respond_to do |format|
        format.html { render :action => "edit", :status => :bad_request }
        format.xml  { render :xml => @session.errors, :status => :bad_request }
      end
    else
      program = @camp.programs.find(params[:program_id])
      if program.is_valid_age(@camper.age)
        ca = CamperAttendance.where("camper_id = ? AND session_id = ?", @camper.id, @session.id).limit(1)[0]

        program_pop = ProgramPopulation.where("program_id = ? AND session_id = ?", ca.program_id, @session.id).limit(1)[0]
        program_pop.decrement!(:current_population)
      
        ca.program_id = params[:program_id]
        program_pop = ProgramPopulation.where("program_id = ? AND session_id = ?", params[:program_id], @session.id).limit(1)[0]
        
        if program_pop
          program_pop.increment!(:current_population)
          isSuccess = ca.save!

          if isSuccess
            respond_to do |format|
              format.html { render :text => "you have updated the registered camper", :status => :accepted }
              format.xml  { head :accepted }
            end
          else
            respond_to do |format|
                format.html { render :action => "edit", :status => :internal_server_error }
                format.xml {render :xml => @session, :status => :internal_server_error, :location => @camper}
            end
          end
        else
          respond_to do |format|
              format.html { render :action => "edit", :status => :bad_request }
              format.xml {render :xml => @camper, :status => :bad_request, :location => @session}
          end
        end
      else
        respond_to do |format|
            format.html { render :action => "edit", :status => :bad_request }
            format.xml {render :xml => @camper, :status => :bad_request, :location => @session}
        end
      end
    end
  end

  # == DELETE /camps/{camp_id}/contacts/{id}
  #
  # Remove the camper from attending a given session
  #
  # === Response Codes: *TODO*
  #
  # * 202 Accepted
  # * 400 Bad Request
  # * 401 Unauthorized
  #
  def destroy
    ca = CamperAttendance.where("camper_id = ? AND session_id = ?", @camper.id, @session.id).limit(1)[0]
    
    program_pop = ProgramPopulation.where("program_id = ? AND session_id = ?", ca.program_id, @session.id).limit(1)[0]
    program_pop.decrement!(:current_population)
    
    ca.destroy
    
    if ca.destroyed?
      respond_to do |format|
        format.html { render :text => "you have updated the registered camper", :status => :accepted }
        format.xml  { head :accepted }
      end
    end
  end
  
  private
    def get_camp
      @camp = Camp.find_by_uri(params[:camp_id])
      if !@camp
        #call parent 404 method because no record was found
        #ActiveRecord::RecordNotFound is not being called
        self.render_404
      end
    end
    
    def get_camper
      @camper = @camp.campers.find(params[:camper_id])
      if !@camper
        #call parent 404 method because no record was found
        #ActiveRecord::RecordNotFound is not being called
        self.render_404
      end
    end
    
    def get_session
      @session = @camper.sessions.find(params[:id])
      if !@session
        #call parent 404 method because no record was found
        #ActiveRecord::RecordNotFound is not being called
        self.render_404
      end
    end
end

app/helpers/camp/campers/sessions_helper.rb
module Camp::Campers::SessionsHelper
end

app/helpers/camp/campers_helper.rb
module Camp::CampersHelper
end

app/helpers/campers_helper.rb
module CampersHelper
end

app/views/campers/edit.html.erb
<h1>Editing camper</h1>

<%= form_for(@camper) do |f| %>
  
  <% @camper.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
  <% end %>

  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </p>
  <p>
    <%= f.label :birthday %><br />
    <%= f.datetime_select :birthday %>
  </p>
  <p>
    <%= f.label :grade %><br />
    <%= f.text_field :grade %>
  </p>
  <p>
    <%= f.label :gender %><br />
    <%= f.check_box :gender %>
  </p>
	<% for camp in Camp.all %>
	<div>
	  <%= check_box_tag "camper[camp_ids][]", camp.id, @camper.camps.include?(camp) %>
	  <%= camp.name %>
	</div>
	<% end %>
  <p>
    <%= f.submit 'Update' %>
  </p>
<%= end %>

<%= link_to 'Show', @camper %> |
<%= link_to 'Back', campers_path %>

app/views/campers/index.html.erb
<h1>Listing campers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Middle name</th>
    <th>List name</th>
    <th>Age</th>
    <th>Birthday</th>
    <th>Grade</th>
    <th>Gender</th>
	<th>Camp</th>
  </tr>

<% @campers.each do |camper| %>
  <tr>
    <td><%=h camper.first_name %></td>
    <td><%=h camper.middle_name %></td>
    <td><%=h camper.last_name %></td>
    <td><%=h camper.age %></td>
    <td><%=h camper.birthday %></td>
    <td><%=h camper.grade %></td>
    <td><%=h camper.gender %></td>
	<% camper.camps.each do |camp| %>
		<td><%=h camp.name %></td>
	<% end %>
    <td><%= link_to 'Show', camper %></td>
    <td><%= link_to 'Edit', edit_camper_path(camper) %></td>
    <td><%= link_to 'Destroy', camper, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New camper', new_camper_path %>

app/views/campers/index.json.erb
[
<% @campers.each_with_index do |camper, index| %>	
	{
		id: <%= camper.id %>,
		first_name: "<%= camper.first_name %>",
		last_name: "<%= camper.last_name %>",
		suffix: "<%= camper.suffix %>",
		age: <%= camper.age %>,
		birthday: "<%= camper.birthday %>",
		grade: <%= camper.grade %>,
		gender: "<%= camper.gender %>",
		camps: [
		<% camper.camps.each_with_index do |camp, index| %>
			{
				camp_uri: "<%= camp.uri %>"
			<% if index == camper.camps.length-1 then %>
			}
			<% else %>
			},
			<% end %>
		<% end %>
		],
		guardians: [
		<% camper.guardians.each_with_index do |guardian, index| %>
			{
				first_name: "<%= guardian.first_name %>",
				middle_name: "<%= guardian.middle_name %>",
				last_name: "<%= guardian.last_name %>",
				suffix: "<%= guardian.suffix %>",
				email_address: "<%= guardian.email_address %>",
				day_phone: "<%= guardian.day_phone %>",
				evening_phone: "<%= guardian.evening_phone %>",
				mobile_phone: "<%= guardian.mobile_phone %>"
			<% if index == camper.guardians.length-1 then %>
			}
			<% else %>
			},
			<% end %>
		<% end %>
		],
		address: {
			street_1: "<%= camper.address.street_1 %>",
			street_2: "<%= camper.address.street_2 %>",
			city: "<%= camper.address.city %>",
			state: "<%= camper.address.state %>",
			zip_code: "<%= camper.address.zip_code %>",
			country: "<%= camper.address.country %>"
		}
	<% if index == @campers.length-1 then %>
	}
	<% else %>
	},
	<% end %>
<% end %>
]

app/views/campers/new.html.erb
<h1>New camper</h1>

<%= form_for(@camper) do |f| %>
  
  <% @camper.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
  <% end %>

  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :birthday %><br />
    <%= f.datetime_select :birthday %>
  </p>
  <p>
    <%= f.label :grade %><br />
    <%= f.text_field :grade %>
  </p>
  <p>
    <%= f.label :gender %><br />
    <%= f.check_box :gender %>
  </p>

	<% for camp in Camp.all %>
	<div>
	  <%= check_box_tag "camper[camp_ids][]", camp.id, @camper.camps.include?(camp) %>
	  <%= camp.name %>
	</div>
	<% end %>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', campers_path %>

app/views/campers/show.html.erb
<p>
  <b>First name:</b>
  <%=h @camper.first_name %>
</p>

<p>
  <b>Middle name:</b>
  <%=h @camper.middle_name %>
</p>

<p>
  <b>List name:</b>
  <%=h @camper.last_name %>
</p>

<p>
  <b>Age:</b>
  <%=h @camper.age %>
</p>

<p>
  <b>Birthday:</b>
  <%=h @camper.birthday %>
</p>

<p>
  <b>Grade:</b>
  <%=h @camper.grade %>
</p>

<p>
  <b>Gender:</b>
  <%=h @camper.gender %>
</p>

<p>
  <b>Camps:</b>
  	<% @camper.camps.each do |camp| %>
		<%=h camp.name %>
	<% end %>
</p>


<%= link_to 'Edit', edit_camper_path(@camper) %> |
<%= link_to 'Back', campers_path %>

app/views/campers/show.json.erb
{
	id: <%= @camper.id %>,
	first_name: "<%= @camper.first_name %>",
	last_name: "<%= @camper.last_name %>",
	suffix: "<%= @camper.suffix %>",
	age: <%= @camper.age %>,
	birthday: "<%= @camper.birthday %>",
	grade: <%= @camper.grade %>,
	gender: "<%= @camper.gender %>",
	camps: [
	<% @camper.camps.each_with_index do |camp, index| %>
		{
			camp_uri: "<%= camp.uri %>"
		<% if index == @camper.camps.length-1 then %>
		}
		<% else %>
		},
		<% end %>
	<% end %>
	],
	guardians: [
	<% @camper.guardians.each_with_index do |guardian, index| %>
		{
			first_name: "<%= guardian.first_name %>",
			middle_name: "<%= guardian.middle_name %>",
			last_name: "<%= guardian.last_name %>",
			suffix: "<%= guardian.suffix %>",
			email_address: "<%= guardian.email_address %>",
			day_phone: "<%= guardian.day_phone %>",
			evening_phone: "<%= guardian.evening_phone %>",
			mobile_phone: "<%= guardian.mobile_phone %>"
		<% if index == @camper.guardians.length-1 then %>
		}
		<% else %>
		},
		<% end %>
	<% end %>
	],
	address: {
		street_1: "<%= @camper.address.street_1 %>",
		street_2: "<%= @camper.address.street_2 %>",
		city: "<%= @camper.address.city %>",
		state: "<%= @camper.address.state %>",
		zip_code: "<%= @camper.address.zip_code %>",
		country: "<%= @camper.address.country %>"
	}
}